### ISSUE TITLE
New movement_template in last edo firmware 3.1.0

### ISSUE THREAD

**Issue by Moreno-Borsalino** [Comau/pyedo#3]
Hi,
in the new firmware 3.1.0 the message MovementCommand got e new field payload. When do you update movement_template in pyedo to the last firmware version ?
Can you also explain what Payload fields means ? They are very strange.
Thanks

**Comment by eDO-Comau** [comment]
Hello, we have a new version release of the pyedo library.
Check that out and notice that we change with camelCase all the functions name in order to meke everything more uniform
